FROM openjdk:17
EXPOSE 8080
ADD target/ApplicationProcessingService-0.0.1-SNAPSHOT.jar ApplicationProcessingService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ApplicationProcessingService-0.0.1-SNAPSHOT.jar"]