kind: Service
apiVersion: v1
metadata:
  name: application-processing
  labels:
    app: application-processing
spec:
  selector:
    app: application-processing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-processing
  labels:
    app: application-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-processing
  template:
    metadata:
      labels:
        app: application-processing
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "application-processing"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: application-processing
          image: application-processing:1.0
          env:
            - name: APP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          imagePullPolicy: Never